apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: backend-local-hostpath
  resources:
    requests:
      storage: 1Gi
