apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: team-todo-board-backend:for-k8s
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8000
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
          env:
            - name: DATABASE_URL
              value: sqlite:////app/data/todos.db
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: backend-data-pvc
